name: postgrest
description: Listen to realtime updates to your PostgreSQL database.
version: 0.0.1-dev.7
homepage: "https://supabase.io"
repository: "https://github.com/supabase/postgrest-dart"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.1.0

dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.9.0
